var App = require('./app');

App.Router.map(function() {
  
  // generated by ember-generate --scaffold
  this.resource('shows');
  this.resource('show', {path: '/shows/:show_id'});
  this.route('edit_show', {path: '/shows/:show_id/edit'});
  this.route('new_show', {path: '/shows/new'});
  // end generated routes

  // This is the login route
  this.route('login');
  // And routes that are inaccessible without logging in:
  this.route('protected');

  this.route('account',{path: '/account'});

  // generated by ember-generate --scaffold
  this.resource('channels');
  this.resource('channel', {path: '/channels/:channel_id'});
  this.route('edit_channel', {path: '/channels/:channel_id/edit'});
  this.route('new_channel', {path: '/channels/new'});
  // end generated routes


  // generated by ember-generate --scaffold
  this.resource('countries');
  this.resource('country', {path: '/countries/:country_id'});
  this.route('edit_country', {path: '/countries/:country_id/edit'});
  this.route('new_country', {path: '/countries/new'});
  // end generated routes


  // generated by ember-generate --scaffold
  this.resource('episodes');
  this.resource('episode', {path: '/episodes/:episode_id'});
  this.route('edit_episode', {path: '/episodes/:episode_id/edit'});
  this.route('new_episode', {path: '/episodes/new'});
  // end generated routes

  this.resource('users');
  this.resource('user', { path: '/user/:user_id'});

});

// Set the base URL
App.Router.reopen({
  rootURL: '/front-end/'
});





// All "protected" routes should require authorization (verify session token)
App.ProtectedRoute = Ember.Route.extend(Ember.SimpleAuth.AuthenticatedRouteMixin, {
  // Authorize request!
  model: function(){
    return new Ember.RSVP.Promise(function(resolve, reject){
      Ember.$.get('/api/data').then(function(response){
        resolve(JSON.stringify(response));
      });
    });
  }
});

// Apply mixins for authentication :)
App.ApplicationRoute = Ember.Route.extend(Ember.SimpleAuth.ApplicationRouteMixin,{
    actions: {
      logSession: function(){
        console.log(session);
      }
    }
});

App.IndexRoute = Ember.Route.extend({
  redirect: function(){
    // Redirect index to shows
    this.transitionToAnimated('shows',{main: 'slideOverLeft'});
  }
});



