var App = require('./app');

App.Router.map(function() {
  
  // generated by ember-generate --scaffold
  this.resource('shows');
  this.resource('show', {path: '/shows/:show_id'});
  this.route('edit_show', {path: '/shows/:show_id/edit'});
  this.route('new_show', {path: '/shows/new'});
  // end generated routes

  this.route('login');

  // generated by ember-generate --scaffold
  this.resource('channels');
  this.resource('channel', {path: '/channels/:channel_id'});
  this.route('edit_channel', {path: '/channels/:channel_id/edit'});
  this.route('new_channel', {path: '/channels/new'});
  // end generated routes


  // generated by ember-generate --scaffold
  this.resource('countries');
  this.resource('country', {path: '/countries/:country_id'});
  this.route('edit_country', {path: '/countries/:country_id/edit'});
  this.route('new_country', {path: '/countries/new'});
  // end generated routes


  // generated by ember-generate --scaffold
  this.resource('episodes');
  this.resource('episode', {path: '/episodes/:episode_id'});
  this.route('edit_episode', {path: '/episodes/:episode_id/edit'});
  this.route('new_episode', {path: '/episodes/new'});
  // end generated routes

  this.resource('users');
  this.resource('user', { path: '/user/:user_id'});

});

// Route for login!
App.ApplicationRoute = Ember.Route.extend(Ember.SimpleAuth.ApplicationRouteMixin);

// Route action for displaying modal popup boxes, 
// can be easily called with {{action 'modal' 'template'}}
App.ApplicationRoute = Ember.Route.extend({
    actions: {
      showModal: function(template){
        return this.render(template, {
          into: 'application',
          outlet: 'modal'
        })
      },
      closeModal: function(template){
        return this.disconnectOutlet({
          outlet: 'modal',
          parentView: 'application'
        });
      }
    }
});

App.IndexRoute = Ember.Route.extend({
  redirect: function(){
    // Redirect index to shows
    this.transitionToAnimated('shows',{main: 'slideOverLeft'});
  }
});

