// This file is auto-generated by `ember build`.
// You should not modify it.

var App = window.App = require('./config/app');
require('./templates');
require('./helpers/comparison');
require('./helpers/comparison.js~');
require('./helpers/dateformat');
require('./helpers/markdown');
require('./helpers/markdown.js~');


App.AccountController = require('./controllers/account_controller');
App.CalendarController = require('./controllers/calendar_controller');
App.ChannelController = require('./controllers/channel_controller');
App.CountryController = require('./controllers/country_controller');
App.EditCountryController = require('./controllers/edit_country_controller');
App.EpisodeController = require('./controllers/episode_controller');
App.EpisodesController = require('./controllers/episodes_controller');
App.InfoController = require('./controllers/info_controller');
App.LoginController = require('./controllers/login_controller');
App.NavigationController = require('./controllers/navigation_controller');
App.NewCountryController = require('./controllers/new_country_controller');
App.ShowController = require('./controllers/show_controller');
App.ShowsController = require('./controllers/shows_controller');
App.UserController = require('./controllers/user_controller');
App.WatchedController = require('./controllers/watched_controller');
App.WatchedShowController = require('./controllers/watched_show_controller');
App.Channel = require('./models/channel');
App.Country = require('./models/country');
App.Episode = require('./models/episode');
App.Role = require('./models/role');
App.Show = require('./models/show');
App.User = require('./models/user');
App.AccountRoute = require('./routes/account_route');
App.CalendarRoute = require('./routes/calendar_route');
App.ChannelsRoute = require('./routes/channels_route');
App.CountriesRoute = require('./routes/countries_route');
App.EpisodesRoute = require('./routes/episodes_route');
App.InfoRoute = require('./routes/info_route');
App.LoginRoute = require('./routes/login_route');
App.NewChannelRoute = require('./routes/new_channel_route');
App.NewCountryRoute = require('./routes/new_country_route');
App.NewEpisodeRoute = require('./routes/new_episode_route');
App.NewShowRoute = require('./routes/new_show_route');
App.ShowRoute = require('./routes/show_route');
App.ShowsRoute = require('./routes/shows_route');
App.ShowsSearchRoute = require('./routes/shows_search_route');
App.UserRoute = require('./routes/user_route');
App.WatchedRoute = require('./routes/watched_route');
App.AccountView = require('./views/account_view');
App.CalendarView = require('./views/calendar_view');
App.EpisodesView = require('./views/episodes_view');
App.InfoView = require('./views/info_view');
App.LoadingView = require('./views/loading_view');
App.LoginView = require('./views/login_view');
App.NavigationView = require('./views/navigation_view');
App.ShowItemView = require('./views/show_item_view');
App.ShowView = require('./views/show_view');
App.ShowsView = require('./views/shows_view');
App.UserView = require('./views/user_view');
App.WatchedShowView = require('./views/watched_show_view');
App.WatchedView = require('./views/watched_view');

require('./config/routes');

module.exports = App;

